- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create SSL directory
  file:
    path: /etc/nginx/ssl/akhavanpour.com
    state: directory
    mode: '0700'

- name: Copy SSL certificate
  copy:
    content: "{{ vault_ssl_cert }}"
    dest: /etc/nginx/ssl/akhavanpour.com/cert.pem
    mode: '0600'

- name: Copy SSL private key
  copy:
    content: "{{ vault_ssl_key }}"
    dest: /etc/nginx/ssl/akhavanpour.com/key.pem
    mode: '0600'

- name: Copy nginx grafana config
  template:
    src: grafana.conf.j2
    dest: /etc/nginx/sites-available/grafana

- name: Enable grafana site
  file:
    src: /etc/nginx/sites-available/grafana
    dest: /etc/nginx/sites-enabled/grafana
    state: link
    force: yes

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
